---
version: '3'

services:
  em-hrs-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=emhrs
      - POSTGRES_USER=emhrs
      - POSTGRES_PASSWORD=emhrs
    ports:
      - 5432:5432

  azure-storage-emulator-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    command: "azurite-blob --blobHost 0.0.0.0 --loose"
    volumes:
      - em-hrs-docker-azure-blob-data:/opt/azurite/folder

volumes:
  pacts:
  em-hrs-docker-azure-blob-data:
