management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: Hearing Recordings Service

  jpa:
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 5
          batch_versioned_data: true
  main:
    allow-bean-definition-overriding: true

  liquibase:
    enabled: ${ENABLE_DB_MIGRATE:true}
    change-log: classpath:/db/db.changelog-master.xml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emhrs}
    username: ${SPRING_DATASOURCE_USERNAME:emhrs}
    password: ${SPRING_DATASOURCE_PASSWORD:emhrs}
