spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:/testdb/db.changelog-master.yaml
    contexts: test

logging:
  level:
    liquibase: INFO
